<?php

use Drupal\user\Entity\User;

/**
 * Implements hook_user_format_name_alter().
 */
function custom_display_name_user_format_name_alter(&$name, $account) {

  $output = '';
  $fields = [];
  $namefields = \Drupal::entityTypeManager()->getStorage('namefield')->loadMultiple();

  foreach ($namefields as $namefield) {
    if (trim($namefield->field_id) != '') {
      $fields[] = array(
        'weight' => $namefield->weight,
        'field_id' => $namefield->field_id,
      );
    }
  }

  if (count($fields) > 0) {

    $entity = User::load($account->id());
    uasort($fields, array('Drupal\Component\Utility\SortArray', 'sortByWeightElement'));

    foreach($fields as $field) {
      if ($entity && $entity->hasField($field['field_id'])) {
        $output .= $entity->{$field['field_id']}->value;
        $output .= ' ';
      }
    }

    $output = trim($output);
    $output = preg_replace('!\s+!', ' ', $output); // no repeating spaces

    if ($output != '') {
      $name = t($output);
    }

  }

}
